server:
  port: 80

eureka:
  client:
    registerWithEureka: false # 服务注册，false表示不将本消费者注册到 Eureka 服务器
    fetchRegistry: true # 服务发现，true从 Eureka 服务器中获取注册信息
    serviceUrl:
      defaultZone: http://eureka6001.com:6001/eureka/,http://eureka6002.com:6002/eureka/
spring:
  application:
    name: feign-consumer
#feign-consumer:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule